<?xml version="1.0"?>
<package format="2">
  <name>ual_planner_bringup</name>
  <version>0.1.0</version>
  <description>ROS Noetic launch and configuration for UAL-planner.</description>
  <maintainer email="TODO@example.com">TODO</maintainer>
  <license>TODO</license>
  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>ins_seg</exec_depend>
  <exec_depend>landing_evaluator</exec_depend>
  <exec_depend>livox_avia_driver</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
</package>
